### ISSUE TITLE
请问能否提供一下文中包含其他对比模型的代码

### ISSUE THREAD

**Issue by w764567792** [AnsongLi/Disen-GNN#1]
作者您好，非常喜欢您的文章，观察到您提供的代码为本文模型代码，请问能否补充一下其他对比模型代码以方便对比复现，若一一整合太过复杂，故想参考您的代码是如何对比的（仅作参考用），万分感谢！

**Comment by AnsongLi** [comment]
抱歉哈，我已经不在当时完成这篇论文的地方实习了，我目前只保留了论文模型代码。其实你将本文的模型代码看懂很容易复现实验中的代码。
